# production
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://db-dev-hy.connectto.int:6033/connectto?useUnicode=yes&characterEncoding=UTF8&autoReconnect=true
  username: connectto_user
  password: T4-vXsDwXd13
  maximumPoolSize: 75
  minimumIdle: 5
  connectionTimeout: 7000
  maxLifetime: 60000
  cachePrepStmts: true
  prepStmtCacheSize: 250
  prepStmtCacheSqlLimit: 2048
  useServerPrepStmts: true
  validation-query: SELECT 1 FROM dual
  poolName: RestHikariCP
  dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource

spring.jpa:
  hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    ddl-auto: none
    show-sql: true

hibernate.ejb.use_class_enhancer: true

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

#logging:
level:
  org.springframework:
    security: DEBUG

#Guide config
guide:
  blockPassword: 1111